2024-04-08 05:46:53,520 INFO    MainThread:9656 [wandb_setup.py:_flush():76] Current SDK version is 0.16.4
2024-04-08 05:46:53,520 INFO    MainThread:9656 [wandb_setup.py:_flush():76] Configure stats pid to 9656
2024-04-08 05:46:53,520 INFO    MainThread:9656 [wandb_setup.py:_flush():76] Loading settings from C:\Users\sazegar\.config\wandb\settings
2024-04-08 05:46:53,520 INFO    MainThread:9656 [wandb_setup.py:_flush():76] Loading settings from C:\Users\sazegar\mir\logic\core\wandb\settings
2024-04-08 05:46:53,520 INFO    MainThread:9656 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-04-08 05:46:53,520 INFO    MainThread:9656 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-04-08 05:46:53,522 INFO    MainThread:9656 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'logic\\core\\evaluation.py', 'program_abspath': 'C:\\Users\\sazegar\\MIR\\logic\\core\\evaluation.py', 'program': 'evaluation.py'}
2024-04-08 05:46:53,522 INFO    MainThread:9656 [wandb_init.py:_log_setup():526] Logging user logs to C:\Users\sazegar\mir\logic\core\wandb\run-20240408_054653-44tx727z\logs\debug.log
2024-04-08 05:46:53,522 INFO    MainThread:9656 [wandb_init.py:_log_setup():527] Logging internal logs to C:\Users\sazegar\mir\logic\core\wandb\run-20240408_054653-44tx727z\logs\debug-internal.log
2024-04-08 05:46:53,522 INFO    MainThread:9656 [wandb_init.py:init():566] calling init triggers
2024-04-08 05:46:53,522 INFO    MainThread:9656 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {}
2024-04-08 05:46:53,523 INFO    MainThread:9656 [wandb_init.py:init():616] starting backend
2024-04-08 05:46:53,523 INFO    MainThread:9656 [wandb_init.py:init():620] setting up manager
2024-04-08 05:46:53,526 INFO    MainThread:9656 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn, using: spawn
2024-04-08 05:46:53,531 INFO    MainThread:9656 [wandb_init.py:init():628] backend started and connected
2024-04-08 05:46:53,536 INFO    MainThread:9656 [wandb_init.py:init():720] updated telemetry
2024-04-08 05:46:53,584 INFO    MainThread:9656 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2024-04-08 05:46:54,078 ERROR   MainThread:9656 [wandb_init.py:init():779] encountered error: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 403: Forbidden)
2024-04-08 05:46:54,168 ERROR   MainThread:9656 [wandb_init.py:init():1194] It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 403: Forbidden)
Traceback (most recent call last):
  File "C:\Users\sazegar\AppData\Local\Programs\Python\Python38\lib\site-packages\wandb\sdk\wandb_init.py", line 1176, in init
    run = wi.init()
  File "C:\Users\sazegar\AppData\Local\Programs\Python\Python38\lib\site-packages\wandb\sdk\wandb_init.py", line 785, in init
    raise error
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 403: Forbidden)
2024-04-08 05:46:55,176 WARNING MsgRouterThr:9656 [router.py:message_loop():77] message_loop has been closed
