2024-04-06 03:43:33,198 INFO    MainThread:22644 [wandb_setup.py:_flush():76] Current SDK version is 0.16.4
2024-04-06 03:43:33,198 INFO    MainThread:22644 [wandb_setup.py:_flush():76] Configure stats pid to 22644
2024-04-06 03:43:33,198 INFO    MainThread:22644 [wandb_setup.py:_flush():76] Loading settings from C:\Users\sazegar\.config\wandb\settings
2024-04-06 03:43:33,198 INFO    MainThread:22644 [wandb_setup.py:_flush():76] Loading settings from C:\Users\sazegar\mir\logic\core\wandb\settings
2024-04-06 03:43:33,198 INFO    MainThread:22644 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-04-06 03:43:33,198 INFO    MainThread:22644 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-04-06 03:43:33,199 INFO    MainThread:22644 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'logic\\core\\evaluation.py', 'program_abspath': 'C:\\Users\\sazegar\\MIR\\logic\\core\\evaluation.py', 'program': 'evaluation.py'}
2024-04-06 03:43:33,199 INFO    MainThread:22644 [wandb_init.py:_log_setup():526] Logging user logs to C:\Users\sazegar\mir\logic\core\wandb\run-20240406_034333-x90fc3m3\logs\debug.log
2024-04-06 03:43:33,199 INFO    MainThread:22644 [wandb_init.py:_log_setup():527] Logging internal logs to C:\Users\sazegar\mir\logic\core\wandb\run-20240406_034333-x90fc3m3\logs\debug-internal.log
2024-04-06 03:43:33,199 INFO    MainThread:22644 [wandb_init.py:init():566] calling init triggers
2024-04-06 03:43:33,199 INFO    MainThread:22644 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {}
2024-04-06 03:43:33,199 INFO    MainThread:22644 [wandb_init.py:init():616] starting backend
2024-04-06 03:43:33,199 INFO    MainThread:22644 [wandb_init.py:init():620] setting up manager
2024-04-06 03:43:33,200 INFO    MainThread:22644 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn, using: spawn
2024-04-06 03:43:33,203 INFO    MainThread:22644 [wandb_init.py:init():628] backend started and connected
2024-04-06 03:43:33,206 INFO    MainThread:22644 [wandb_init.py:init():720] updated telemetry
2024-04-06 03:43:33,245 INFO    MainThread:22644 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2024-04-06 03:43:33,606 ERROR   MainThread:22644 [wandb_init.py:init():779] encountered error: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 403: Forbidden)
2024-04-06 03:43:34,180 ERROR   MainThread:22644 [wandb_init.py:init():1194] It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 403: Forbidden)
Traceback (most recent call last):
  File "C:\Users\sazegar\AppData\Local\Programs\Python\Python38\lib\site-packages\wandb\sdk\wandb_init.py", line 1176, in init
    run = wi.init()
  File "C:\Users\sazegar\AppData\Local\Programs\Python\Python38\lib\site-packages\wandb\sdk\wandb_init.py", line 785, in init
    raise error
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 403: Forbidden)
2024-04-06 03:43:35,192 WARNING MsgRouterThr:22644 [router.py:message_loop():77] message_loop has been closed
